### ISSUE TITLE
File Versioning

### ISSUE THREAD

**Issue by luke-** [humhub/cfiles#121]
Currently, when a file with the same file name is uploaded, it is overwritten or a new file is created depending on the configuration.
An edited file (e.g. via OnlyOffice) is always overwritten.

In future, a new version of the file should always be created in these cases. 

In the context menu, there should be a link "Versions", which opens a modal that allows access and restore of older versions.

---

A `CFile` (module) consequently has several `File` (file) models.

--- 

Also related to: https://github.com/humhub/cfiles/issues/122#issuecomment-905188028

**Comment by luke-** [comment]
https://github.com/humhub/cfiles/issues/113

**Comment by yurabakhtin** [comment]
@luke- 

> Currently, when a file with the same file name is uploaded, it is overwritten or a new file is created depending on the configuration.

Sorry, I cannot find such configuration, please tell me.

> In the context menu, there should be a link "Versions", which opens a modal that allows access and restore of older versions.

Do you tell about files which are stored on disc and not in DB, if yes then where do you plan to store the old versions, also on the disc, i.e. after each update we should create an additional file with some suffix of the modification date?

**Comment by luke-** [comment]
@yurabakhtin Here the configuration part:
![image](https://user-images.githubusercontent.com/4736168/132531968-59353217-b97a-49f3-a98c-383ced549c0f.png)

No, the Idea is this:
Currently: Each file entry in the CFiles module `humhub\modules\cfiles\models\File` is currently associated with exactly one `humhub\modules\cfiles\models\File`. 

With versioning, each `humhub\modules\cfiles\models\file` should be able to have multiple  `humhub\modules\cfiles\models\File` records. (For each file version one.)

**Comment by yurabakhtin** [comment]
@luke- Ok, thanks for the info, however in your examples the same class so I think you mean this:

- Currently: `humhub\modules\cfiles\models\File` is associated with **single** core `humhub\modules\file\models\File`
- Idea: `humhub\modules\cfiles\models\File` will be associated with **multiple** core `humhub\modules\file\models\File`

Right?

**Comment by luke-** [comment]
@yurabakhtin Yes!

**Comment by yurabakhtin** [comment]
@luke- 

> In the context menu, there should be a link "Versions", which opens a modal that allows access and restore of older versions.

When do you plan to merge the PR https://github.com/humhub/cfiles/pull/131? Because if I will add the new context menu item "Versions" in old version then it will be not easy to merge.
It looks you forgot to merge because I see you merge the core changes but not for the `cfiles` module from the issue https://github.com/humhub/cfiles/issues/127.

**Comment by yurabakhtin** [comment]
@luke- I have started the logic in the commit https://github.com/humhub/cfiles/pull/138/commits/b5e59290883c88f26dc3f4277f3f440fa12652bf:

<img width="1230" alt="file_versioning" src="https://user-images.githubusercontent.com/6995524/132848342-a9f741fc-0eb9-4a82-bc96-f56363e24935.png">

Next step is to implement UI for switching, I will start on old context menu while new is not merged yet.

**Comment by luke-** [comment]
@yurabakhtin Ok great looks good so far!

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/cfiles/pull/138/commits/cea87c1c86b6040cfbbcd1fb9952b0888f2a2283:

<img width="958" alt="file_versions" src="https://user-images.githubusercontent.com/6995524/132881707-a1345bdf-9cc4-4998-8bed-705d7496c170.png">

What I should still do:

- Don't show the context menu item "Versions" if the file has only single version,
- Add tests,
- Probably change the UI from radio list to table view, @luke- please let me know if UI should be changed there somehow.

**Comment by luke-** [comment]
Looks already pretty good!

Probably a table in the version dialog would be nicer.

Columns could be:
Time, Author, Size, Options -> Revert to this version, Download

It would be important that other modules like OnlyOffice or other file editors could work with versioning. Maybe we should provide here some API?

**Comment by yurabakhtin** [comment]
> - Don't show the context menu item "Versions" if the file has only single version,

Commit https://github.com/humhub/cfiles/pull/138/commits/01dc7f927b843aaa26e7828636c9157c5a0001d0

> - Add tests,

Commit https://github.com/humhub/cfiles/pull/138/commits/21b948aecae20e08d9437b72d0f9d6f9c096ce2f

**Comment by yurabakhtin** [comment]
@luke- 

> It would be important that other modules like OnlyOffice or other file editors could work with versioning. Maybe we should provide here some API?

Currently the code model `humhub\modules\file\models\File` doesn't restrict to have multiple records for same object. I.e. each model from other modules can has several records in the table like we implemented for the model `cfiles\models\File`.

If some another model from external module will want to have same multiple File records then code should be changed from the external module side, if we tell about OnlyOffice then I guess here https://github.com/ONLYOFFICE/onlyoffice-humhub/blob/master/models/CreateDocument.php#L91 we should allow to find existing File instead of current `$file = new File();`.

Then I don't understand why we need to implement some API if each external module has an access to core DB tables. I.e. if we need some UI to work with file versions we can get the data directly from DB without API requests.
Also when OpenOffice is created as attachment to a post on stream then we can find the file on the cfiles browser in the folder "Files from the stream" where we may open context menu "Versions".

**Comment by luke-** [comment]
@yurabakhtin "Don't show the context menu item "Versions" if the file has only single version," , sorry for the late feedback, but if you use a table view on this lightbox, we should always show this menu entry. Otherwise it may confuses users.

**Comment by luke-** [comment]
@yurabakhtin Regarding the API: Here is the code line where in the OO Module a change of the document is saved.
https://github.com/ONLYOFFICE/onlyoffice-humhub/blob/master/controllers/BackendController.php#L123

How would the code have to look like to support versioning in CFiles? Maybe a extra API is too much here, but the code should be as simple as possible.
 
Ok, interesting point that versioning could theoretically be possible for files from normal posts as well. However, this is currently not absolutely necessary.

**Comment by luke-** [comment]
@yurabakhtin Here a quick idea/thought: 

The HumHub Core File Model has the attributes `object_model/id` which refer to the related CFile Model.
Would it theoretically also be possible to leave this link `object_model/id` only set for latest file Model record?
Older core File model versions could have a link to the Core File Model itself?

Example:

Current situation:
| id | object_model | object_id | ... | Note                               |
|----|--------------|-----------|-----|------------------------------------|
| 1  | CFile        | 1         |     |                                    |
| 2  | CFile        | 1         |     |                                    |
| 3  | CFile        | 1         |     | Latest file marked in cfiles table |

Idea:
| id | object_model | object_id | ... | Note                               |
|----|--------------|-----------|-----|------------------------------------|
| 1  | File        | 3         |     |                                    |
| 2  | File        | 3         |     |                                    |
| 3  | CFile        | 1         |     |  Latest Version |

**Comment by yurabakhtin** [comment]
@luke- 

> Probably a table in the version dialog would be nicer.
> Columns could be:
> Time, Author, Size, Options -> Revert to this version, Download

Commit https://github.com/humhub/cfiles/commit/401391bc21628f3f27794f1f86623685b2f082ac:

<img width="743" alt="table-view" src="https://user-images.githubusercontent.com/6995524/133261113-df9a1f0b-2d65-499c-9503-5c83d2d5cbae.png">

**Comment by yurabakhtin** [comment]
@luke- 

> "Don't show the context menu item "Versions" if the file has only single version," , sorry for the late feedback, but if you use a table view on this lightbox, we should always show this menu entry. Otherwise it may confuses users.

Sorry, not clear your idea why we should display the "Versions" table when CFile has only single version, please see how it will looks:

<img width="608" alt="single-revision" src="https://user-images.githubusercontent.com/6995524/133261657-0684508f-d2b3-4546-878d-57191429dba1.png">

I.e. there is no the action link to switch to revision because no reason to switch to the same version, so do you still think we should display the context menu item "Versions" and then the table with single row like on my screenshot above?

**Comment by luke-** [comment]
@yurabakhtin Thank you for the screenshot. Yes, I would nevertheless show it, even if only one version is available. That way the user sees that there is a versioning at all.

**Comment by luke-** [comment]
> @luke-
> 
> > Probably a table in the version dialog would be nicer.
> > Columns could be:
> > Time, Author, Size, Options -> Revert to this version, Download
> 
> Commit [401391b](https://github.com/humhub/cfiles/commit/401391bc21628f3f27794f1f86623685b2f082ac):
> 
> <img alt="table-view" width="743" src="https://user-images.githubusercontent.com/6995524/133261113-df9a1f0b-2d65-499c-9503-5c83d2d5cbae.png">

Looks good. But I would prefer that the latest version always appears at the top. If, for example, there are 5 pages with 10 versions each, and you roll back to page 3 of one version, it becomes confusing.

**Comment by yurabakhtin** [comment]
@luke- 

> Yes, I would nevertheless show it, even if only one version is available. That way the user sees that there is a versioning at all.

Ok, commit https://github.com/humhub/cfiles/pull/138/commits/5351fb4f18f8daed6612311143ecd0ffa4870ffd.

**Comment by yurabakhtin** [comment]
@luke- 

> https://github.com/humhub/cfiles/issues/121#issuecomment-919013001
> 
> Would it theoretically also be possible to leave this link `object_model/id` only set for latest file Model record?
> Older core File model versions could have a link to the Core File Model itself?
> 
> What do you think?

From the "Current situation:" table we can know what base/core Files are linked with CFile model, but how can we know this from the "Idea:" table? Currently we select versions by `object_model` and `object_id`. Sorry, but now the idea is not clear for me, also why do you need the linking core File model to itself?

**Comment by luke-** [comment]
@yurabakhtin The main point of my idea is that, theoretically, with the `object_model/id` mapping, a regular `humhub\modules\file\models\File` can also have multiple `humhub\modules\file\models\File` versions.

Example: 
- A  `CFile` has exactly one `File`, which refers to latest version.
 - A `File` also have multiple associated `File` records, which represents are the alternative versions. 

Advantages:

- Only one file is ever assigned to the content model (e.g. CFile). This is always the last and active version.
- This means that no additional field such as `file_id` would be necessary in the `cfiles` or other modules tables. 
- We could implement the versioning and, if necessary, helper methods centralised in the core. I could imagine, for example, that in the long term we need a system to combine many changes within a short period of time from several versions into one version in order to save memory.

Disadvantages:

- A little more complex.
- It is a little more complicated from the lookup

**Comment by luke-** [comment]
Here is an example code of how the code on the core side might look like:
https://github.com/humhub/humhub/compare/develop...enh/file-versioning


Example how to rollback to a version:
```php

/** @var humhub\modules\file\models\File $file */
/** @var humhub\modules\file\models\File $previousFileVersion */

$previousFileVersion = $file->getFileVersionsQuery()->limit(1)->one();
$file->replaceWithFile($previousFileVersion);
```

**Comment by yurabakhtin** [comment]
@luke- Thank you for the details, yes now I got it, so if we have these data:

| id | object_model | object_id | ... | Note                               |
|----|--------------|-----------|-----|------------------------------------|
| 1  | File        | 3         |     |                                    |
| 2  | File        | 3         |     |                                    |
| 3  | CFile        | 1         |     |  Latest Version |

after uploading new CFile the data will be updated to this:

| id | object_model | object_id | ... | Note                               |
|----|--------------|-----------|-----|------------------------------------|
| 1  | File        | 4         |     |                                    |
| 2  | File        | 4         |     |                                    |
| 3  | File        | 4         |     |                                    |
| 4  | CFile        | 1         |     |  Latest Version |

on switching the CFile#1 to the version File#2 the data will be like this:

| id | object_model | object_id | ... | Note                               |
|----|--------------|-----------|-----|------------------------------------|
| 1  | File        | 2         |     |                                    |
| 2  | CFile        | 1         |     |  Latest Version |
| 3  | File        | 2         |     |                                    |
| 4  | File        | 2         |     |                                    |

I will implement core helpers to work with such versions algorithm.

**Comment by yurabakhtin** [comment]
@luke- I have implemented the file versioning from core side in PR https://github.com/humhub/humhub/pull/5293.
The related changes for the cfiles module in the commit https://github.com/humhub/cfiles/commit/0dc6c26fa6071be1ff74cf20b0b18dca1b57dd29.

---

You didn't answer yet on the question:

> You tell about pages, should I implement the pagination for the table?

but I think we need this because it looks like this:

<img width="1153" alt="need_pagination" src="https://user-images.githubusercontent.com/6995524/133783383-765e5e77-c185-423f-9ed0-f5e0bf589a14.png">

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/cfiles/pull/138/commits/e1881ca8c3fb646dc396dea706316ebf7d046695 - Pagination for file versions table:

<img width="610" alt="versions-pagination" src="https://user-images.githubusercontent.com/6995524/133819495-a4bdc0c5-9623-4083-97eb-6112aeabe4aa.png">

Single page:

<img width="609" alt="single_page" src="https://user-images.githubusercontent.com/6995524/133819527-5601cdeb-7ca3-4f36-8e92-f3191338233a.png">

**Comment by yurabakhtin** [comment]
@luke- Please note the PR has errors in tests https://github.com/humhub/cfiles/runs/3634226999?check_suite_focus=true#step:25:31 because the branch `develop` need new changes from the core PR https://github.com/humhub/humhub/pull/5293.

**Comment by luke-** [comment]
@yurabakhtin Awesome & Thanks, please see my PR reviews. Looks quite nice thanks!  Can you please also prepare a **draft** PR which provides versioning here. https://github.com/ONLYOFFICE/onlyoffice-humhub

**Comment by yurabakhtin** [comment]
@luke- Could you please provide me with some test server so I will check how the module store files?
Currently I can test this only without editing files, but please note it is possible to create several files with same name for a post:

<img width="1005" alt="test_same_file_names" src="https://user-images.githubusercontent.com/6995524/134008675-451d4712-2428-4eee-a707-d633bec73ccf.png">

I guess on edit a file it is stored into the same `File`, i.e. new record it not created in the table `file`, but you want to create a new record instead of previous, and previous record should be linked to the current with `object_model = humhub\modules\file\models\File`, right?

Also currently we don't have a context menu like on cfiles browser, should we add a button to view versions here? :
<img width="611" alt="versions" src="https://user-images.githubusercontent.com/6995524/134010418-7b6cc36c-f8ac-4b76-af1e-adb65526b184.png">

**Comment by luke-** [comment]
In my example PR I would also assume that each file modification (CFiles ReUpload, OnlyOffice Edit, Text Editor Edit), 
first creates a new `File` record and then calls this `ReplaceWithFile()` method.
See: https://github.com/humhub/humhub/blob/enh/file-versioning/protected/humhub/modules/file/models/File.php#L284 

In your core PR/apprach (if I understood it correctly) the "replaceWithFile" step happens automatically when
creating/attaching a new `File` using the event `ActiveRecord::EVENT_AFTER_INSERT`.
Does this also work with content where multiple files are added? If yes, we can stick to your approach.

---

An important question to clarify would be whether we want to add Versioning support for all Contents (Posts, Tasks, Wiki)
or only for the `CFiles` module (at least for the beginning).

Here I assumed the second, that we offer Versioning Support optionally for modules and an interface class must be implemented first to enable it. In this case, the `CFiles` could use versioning and the default  `Post` module could just replace the file.  
So depending on where the `File` (CFile or Post) is atteched you could either have versioning or not. https://github.com/humhub/humhub/blob/enh/file-versioning/protected/humhub/modules/file/models/File.php#L294-L302

Alternatively, we can enable versioning for all contents (not only CFiles) directly. 

I think it would be good to maybe start with just the `CFile` module for now and have only the most necessary changes in the core. If the versioning works out, we can move the classes like the `VersionController` later into the Core.

What do you think?

**Comment by yurabakhtin** [comment]
@luke- 

> In your core PR/apprach (if I understood it correctly) the "replaceWithFile" step happens automatically when
creating/attaching a new `File` using the event `ActiveRecord::EVENT_AFTER_INSERT`.
Does this also work with content where multiple files are added? If yes, we can stick to your approach.

In my core PR https://github.com/humhub/humhub/pull/5293/files the "replaceWithFile" step happens automatically on the event `ActiveRecord::EVENT_AFTER_INSERT`, it works like this sample:

If before new uploading a file with same name we have a DB like this:

| id | object_model | object_id | ... | Note                               |
|----|--------------|-----------|-----|------------------------------------|
| 1  | File        | 3         |     |                                    |
| 2  | File        | 3         |     |                                    |
| 3  | CFile        | 1         |     |  Latest Version |

then after uploading new CFile the data will be updated to this:

| id | object_model | object_id | ... | Note                               |
|----|--------------|-----------|-----|------------------------------------|
| 1  | File        | 4         |     |                                    |
| 2  | File        | 4         |     |                                    |
| 3  | File        | 4         |     |                                    |
| 4  | CFile        | 1         |     |  Latest Version |

I.e. firstly we find ID of the previous latest version, in our case ID=3, then update the record (id=3) `object_model: CFile => File` and `object_id: 3 => 4`, also we should find all other old versions i.e. we should do `object_id: 3 => 4` for records with id=1 and id=2. All these actions are executed by single SQL query here https://github.com/humhub/humhub/pull/5293/files#diff-1d69c3220adcc4f2d087e12f111719fb7a477227e335a8640ae4bc26b4f01435R85-R102.
Please note in your example version https://github.com/humhub/humhub/blob/enh/file-versioning/protected/humhub/modules/file/models/File.php#L284-L303 I see only updating the previous version, but there is no updating of all other more older versions.

But I am bit confused here myself because by this logic on attaching a File to a Post all previous attached Files of the Post should become old versions of the latest uploaded, that is wrong indeed because Post should have multiple attached files, and we should not replace previous attached Files. However currently my code doesn't overwrite previous attached files, i.e. on each attaching it works like before:

<img width="1164" alt="attach_to_post" src="https://user-images.githubusercontent.com/6995524/134336061-a1b252c4-4435-4389-ad93-c1e1a66cfbb8.png">

After debug the code I found answer why all previous attached Files stay as separate file of a Post instead of expecting converting to old versions as it works with CFiles:

<img width="741" alt="debug_post_attaching" src="https://user-images.githubusercontent.com/6995524/134338474-a17a97f8-2da7-453c-b9e8-8985edc421cf.png">

I.e. my current code doesn't break files of the Post model, but of course we cannot be sure that it will works with all other model, because if some model will set `object_model` before insert then all previous files of the same model will be converted to old version that will be wrong of course, so I agree we should implement some interface like you suggested `AttachedFileVersioningSupport` and we will run my behaviour `Versions::refreshVersions` only for models with such implemented interface, do you agree this?

----

>I think it would be good to maybe start with just the `CFile` module for now and have only the most necessary changes in the core. If the versioning works out, we can move the classes like the `VersionController` later into the Core.
>
> What do you think?

As I wrote above we should implement some interface as you suggested `AttachedFileVersioningSupport` and on first step use this only for `CFiles` and then we will may apply for other models, but currently we don't have a core UI to work with versions, we have this only from cfiles module side, i.e. probably in future it will be some core UI to review old versions and switching to another version.

**Comment by luke-** [comment]
@yurabakhtin Ok, then let's proceed with interface and "replaceWithFile" method. But we should always (even for modules with non versioning support) use the "replaceWithFile" method to update file contents.

I like the approach that files can't be changed anymore. This opens us good chances in things like caching, CDN, Trashcan...

**Comment by luke-** [comment]
The Versioning UI stuff can be moved from CFiles to Core, with a later version e.g. HumHub v1.11 or v1.12

**Comment by yurabakhtin** [comment]
@luke- Please review new changes in core PR - https://github.com/humhub/humhub/pull/5293/commits/194a6c61f55589e7121a829be5dbe4626f321db6, and in cfiles module - https://github.com/humhub/cfiles/pull/138/commits/8126753d4d5db7bf55540c2e283690910d0120c1.

**Comment by yurabakhtin** [comment]
@luke- I don't find any new comments in the PRs what should be changed there.

**Comment by luke-** [comment]
@yurabakhtin For the core PR there is a comment here: https://github.com/humhub/humhub/pull/5293#pullrequestreview-763215975

We may also need a strategy to clean up older versions. I think for example the OnlyOffice module does an AutoSave every X minutes.

Here some ideas for options:

- Define max. versions per file (e.g. 50)
- Define max. versions per day per file (for versions older than x days)
- Auto Combine combine versions created by a short interval by the same users

We could implement a version cleanup like that later, but we should think about it.

**Comment by yurabakhtin** [comment]
@luke- 

> For the core PR there is a comment here: humhub/humhub#5293 (review)

I answered https://github.com/humhub/humhub/pull/5293#issuecomment-927968757.

**Comment by luke-** [comment]
@yurabakhtin Looks and works great! Can you implement that someone with `ManageFiles` permission can also delete old versions as well?

**Comment by yurabakhtin** [comment]
@luke- 

> Can you implement that someone with `ManageFiles` permission can also delete old versions as well?

Commit https://github.com/humhub/humhub/pull/5311, please note the core fix https://github.com/humhub/humhub/pull/5311 is required to make the deleting of versions working.

**Comment by luke-** [comment]
@yurabakhtin Ok great, is there anything else to do with the issue? I have written a comment at the PR. But otherwise we can merge it? Or is something still missing?

**Comment by luke-** [comment]
@yurabakhtin Yes, please rewrite that, so `$cfile->content->canEdit()` can "View older versions" and restore.

**Comment by luke-** [comment]
@yurabakhtin Thanks! Then the PR should be ready for the time being, right?

**Comment by yurabakhtin** [comment]
@luke- Yes, right, we can merge it.
