### ISSUE TITLE
Align Context Menus

### ISSUE THREAD

**Issue by luke-** [humhub/cfiles#127]
It would be good if we could somehow use the context menu from the Stream Entry with the options in the Cfiles module as well.

**Stream Menu**
![image](https://user-images.githubusercontent.com/4736168/128546678-2993d2c5-73d1-4917-a001-fa224f100007.png)

**File Menu**
![image](https://user-images.githubusercontent.com/4736168/128546715-5ed6d2ee-6b92-4ad4-b8d2-848818d7f5b6.png)

Probably there is a similar need in other places (e.g. Task module).

So probably it would be good if we create the possibility here in the core repo.

**Comment by yurabakhtin** [comment]
@luke- 

> It would be good if we could somehow use the context menu from the Stream Entry with the options in the Cfiles module as well.

Do I understand you correctly: you want to extend the cfiles context menu with additional options from stream menu, i.e. we should add options:

- Topics
- Change to Public
- Lock comments
- Turn off notifications
- Move content
- Move to archive

right?

**Comment by yurabakhtin** [comment]
@luke- What I could implement in PR https://github.com/humhub/cfiles/pull/131 and also small changes are required from core PR https://github.com/humhub/humhub/pull/5261:

<img width="1161" alt="wall-controls-in-context-menu" src="https://user-images.githubusercontent.com/6995524/130794156-00f29fdb-541c-4a13-9022-db8fc94ea321.png">

But there are still errors on click on some of the menu entries because really all they are implemented firstly to work from wall entry under widget `stream.StreamEntry`, so my implementation looks like a hack here https://github.com/humhub/cfiles/pull/131/files#diff-1e2c78de692f3804fd3363931f7ad1f6c388896340f73385de108d7f799cc87fR4 where I just added a wrapper `<div data-ui-widget="stream.StreamEntry">`.

The main difference between stream wall entry menu and cfiles context menu is that wall entry menu is intialized per each entry as separate html tag `<ul>` but for cfiles we have a single `<ul>` that is inialized same for all rows and the action there is called by JS code.

So current version still has errors because after each click on the menu entry we should reload a file row completely as it is done on wall stream entry side, because we need the reloading in order to update state of the menu entries, e.g. "Save as bookmark" vs "Remove from bookmarks". Currently I just blocked the reloading here https://github.com/humhub/humhub/pull/5261/files#diff-9b40039e0bb6ca8e0806ba5ea1c0dda8dde291b8fcebb7010a0c7cc104555833R91 that not good of course, but otherwise JS error.
I.e. we should somehow to find a solution for similar reloading with displaying message in state like "Content successfully removed from bookmarks." and update the context menu, but it is possible only by some additional ajax request because it is rendered on server side and we cannot change this there because it is in external modules like we have in "Content Bookmark".

Should I continue to implement this or do you think this is so complex and no need this feature?

**Comment by luke-** [comment]
@yurabakhtin I think you are already on a good way here. But I think we need to refactor a bit more/deeper to get a nice solution that also works in other modules.

What do you think about introduce new class `ContentControls` which is extended by `WallEntryControls` and only hold menu entries which are not requiring the `Stream Wall Entry` logic?

Do you also see a change to then extend `FileListContextMenu` from this `ContentControls` widget?

So that we end up with the following inheritances:

`Widget` -> `Menu` -> `ContentControls` -> `WallEntryControls`  
`Widget` -> `Menu` -> `ContentControls` -> `FileEntryControls`  

We can then move the entries from `WallEntryControls` to `ContentControls` step by step.

**Comment by luke-** [comment]
@yurabakhtin Thanks for the info. 

Yes, please migrate the `FileListContextMenu` so that it extends  `WallEntryControls`.

I think this is the best way for the the long run, if such menus clearly depend on the `Menu` classes and there is no merge of different appraches.

 I am still considering whether we should not also introduce `ContentControls`. Then we could perhaps remove a few WallEntry only links such as "Pin".

**Comment by yurabakhtin** [comment]
@luke- The migration `FileListContextMenu` is in process.

**Comment by yurabakhtin** [comment]
@luke- I have committed first version of the extended `FileListContextMenu` here https://github.com/humhub/cfiles/pull/131/commits/dc14ee933d46fbce69aae6f8e78808919b0b1803 but it is not works well yet, I need to change JS code to reload row after update like it works on wall stream side.

**Comment by luke-** [comment]
@yurabakhtin ok, thanks for the update

**Comment by yurabakhtin** [comment]
@luke- New update in the commit https://github.com/humhub/cfiles/pull/131/commits/7c6b224c039c40996c23fd5a2efb1f80a154b530, to reload the file row after some stream action, but not all actions still work there, e.g. "Pin" and "Archive" doesn't work.

**Comment by yurabakhtin** [comment]
@luke- In today's commits of these 2 PRs https://github.com/humhub/cfiles/pull/131/commits and https://github.com/humhub/humhub/pull/5261/commits I have fixed all Js errors, so currently all context menu entries works well. They may be merged.

> I am still considering whether we should not also introduce `ContentControls`. Then we could perhaps remove a few WallEntry only links such as "Pin".

To remove the "Pin" entry I just call a code `$this->renderOptions->disableControlsEntryPin();` from `FileListContextMenu` side. I didn't implement `ContentControls` yet because as I wrote it would not solve all JS issues what I fixed today. We might implement the `ContentControls` only for better code order and if you think it will does development easier in future, however we can disable each menu entry from cfiles side as I wrote above. Let me know if I should start this refactoring.

**Comment by luke-** [comment]
@yurabakhtin Thanks looks good. Can you please see my review? 

Regarding the test errors, can you try to update the develop branch in this PR?

**Comment by yurabakhtin** [comment]
@luke- I have done new changes for your remarks - https://github.com/humhub/cfiles/pull/131/commits/eda8f380dcd41d9f30cd753ddf260220fd13733f.

**Comment by luke-** [comment]
@yurabakhtin Here another small UI improvement

![image](https://user-images.githubusercontent.com/4736168/131980887-f572b9bb-af02-4f36-947d-982ddd5ae7a5.png)

**Comment by yurabakhtin** [comment]
@luke- 

> Remove: Can you please add this option to "Move" Dialog as "Move to another Space"

Sorry, not sure what you mean here, probably it was already implemented here https://github.com/humhub/cfiles/issues/84, if yes, then as I got I just need to implement the same for folders.

> Remove: Not supported by CFiles

Why is it not supported, I see it works well as from wall stream side as from cfiles browser page:

<img width="952" alt="archive_cfile" src="https://user-images.githubusercontent.com/6995524/132179164-e37a1444-2078-43fc-ad41-72d1ad5c22f8.png">

---

I have detected one issue and fixed in the commit https://github.com/humhub/cfiles/pull/131/commits/593d52593960b31d869333a863a45a040abe0af6 of the same PR:

<img width="952" alt="archive_cfile" src="https://user-images.githubusercontent.com/6995524/132179320-306cc5f5-928d-48b2-afa3-23a65155e24f.png">

Only one issue we can see here is that the dividers are hidden when the content is archived, it is because in core code the `DropdownDivider::class` is disabled for all archived entries: https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php#L165:

```php
->disableControlsEntry(DropdownDivider::class);
```

I think it should be fixed somehow, either from core side or from CFiles module side.

**Comment by luke-** [comment]
@yurabakhtin Regarding "Move":

It is not clear  where the difference between "Move" and "Move content" is.

![image](https://user-images.githubusercontent.com/4736168/132189866-64025163-e471-4973-a733-5c5306b37ac7.png)


So we should remove "Move content" and add a link  here:

![image](https://user-images.githubusercontent.com/4736168/132190224-15b6c230-2b5e-4379-ad07-04c513bceb63.png)

**Comment by luke-** [comment]
@yurabakhtin Regarding "Archive":

Even if the "Archive" link is working, it has no effect on the view except for the status message.
This is confusing for many users. 

In the Stream view also the Wall Entry disappears.

So the best solution would be at the moment:

CFiles View - Context Menu: Don't show Archive Link
Stream Entry CFiles Context Menu: Show Archive Link as before 


This can probably easily done by a flag, or?

**Comment by yurabakhtin** [comment]
@luke- Thank you for the details with screenshot, I have done all in commit https://github.com/humhub/cfiles/pull/131/commits/dbec8e79e300b269984a8bde0e6f39be3e82fd04, it works like this:

<img width="977" alt="new_move_ui" src="https://user-images.githubusercontent.com/6995524/132220000-28879b03-0472-45e7-ae4d-d37b068547be.png">

---

> CFiles View - Context Menu: Don't show Archive Link

Ok, I have hidden that.

> This can probably easily done by a flag, or?

I think it would be good if we will mark the archived files with some grey background on the files browser page, so in such case user will knows the files is not visible on the wall stream side.

**Comment by luke-** [comment]
@yurabakhtin Thanks, looks good!

Regarding "Archive" I've added a seperate issue #135  - we may optimize this in the future.
