### ISSUE TITLE
Code duplication in File::getIconClassByExt

### ISSUE THREAD

**Issue by dreua** [humhub/cfiles#133]
https://github.com/humhub/cfiles/blob/117d6cc842f3843244837e1129f91b907273f1b7/models/File.php#L240-L303

seems to be somewhat duplicating

https://github.com/humhub/humhub/blob/26d7e2667a9317057abe335a056ac8e8f4d675fb/protected/humhub/libs/MimeHelper.php#L35-L85

Could this be merged / simplified?

**Comment by luke-** [comment]
@yurabakhtin Can you please check?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/cfiles/pull/137: I just factorized the code inside this module `cfiles`, but I don't find how the core code https://github.com/humhub/humhub/blob/26d7e2667a9317057abe335a056ac8e8f4d675fb/protected/humhub/libs/MimeHelper.php#L35-L85 can be factorized with `cfiles` code because there different icons with style class like `.mime-image` instead of `.fa-` icons which are used in the module `cfiles`.

Also during work on this I detected the class `BaseFileRow` is used only for extend `StreamFileRow` but it is not used at all, so we can remove these 2 classes from this module completely. Only static method `BaseFileRow::translateOrder()` is used in one place that can be moved into the helper `FileUtils`. Should I do this factorization in the same PR as well?

**Comment by luke-** [comment]
@yurabakhtin Ok, thanks. Then we leave the code in the core repo as it for now. 

Ok, please to the refactorization in the same PR!

**Comment by yurabakhtin** [comment]
@luke- I was mistaken when I told the class `BaseFileRow`, really it is used for files posted in wall stream.
I just removed the class `StreamFileRow` in commit https://github.com/humhub/cfiles/pull/137/commits/f9fe25812ec22b728968ec336a9cc978b2587a40.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
