### ISSUE TITLE
Usage of new ContentVisibiltySelect

### ISSUE THREAD

**Issue by luke-** [humhub/cfiles#140]
Instead of Checkbox https://github.com/humhub/cfiles/blob/master/views/edit/modal_edit_file.php#L26
use new:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/ui/form/widgets/ContentVisibilitySelect.php

@yurabakhtin Can you please check other modules (e.g. Calendar, Wiki, Tasks) for this?

**Comment by luke-** [comment]
@yurabakhtin Seems the tests are now failing
https://github.com/humhub/cfiles/runs/3666330108?check_suite_focus=true

**Comment by yurabakhtin** [comment]
@luke- 

> @yurabakhtin Can you please check other modules (e.g. Calendar, Wiki, Tasks) for this?

In other places like calendar module we use a form model that is not active record so the widget could not work properly, in order to fix that I did the core PR https://github.com/humhub/humhub/pull/5302, do you agree this? If yes, then we can do such changes in other modules like I did here https://github.com/humhub/calendar/pull/256/files#diff-3caf92d628307372160bea731e6eee8b0fbdceb800c52dbfb1bcb7ffee52c80bR72.

**Comment by luke-** [comment]
@yurabakhtin Yes, the PR looks good. But we schedule it for 1.10 (develop)

**Comment by yurabakhtin** [comment]
@luke- Ok, then I rebased the PR to `develop` branch.

**Comment by yurabakhtin** [comment]
@luke- I have found the following modules where the `extends ContentActiveRecord` is used:

- https://github.com/humhub/calendar/pull/256
- https://github.com/humhub-contrib/gallery/pull/88
- https://github.com/humhub/tasks/pull/165
- https://github.com/humhub/wiki/pull/203
- https://github.com/humhub-contrib/external_calendar/pull/30
