### ISSUE TITLE
Inconsistent context menus after update to version 0.14.2

### ISSUE THREAD

**Issue by psg-webdev** [humhub/cfiles#155]
We use HumHub Professional Edition 1.10.3 with Enterprise Theme 1.7.2.
After updating from version 0.13.1 to 0.14.2 the following phenomenon occurs in the file - listing (cfiles/browse):

Some entries have very short context menus with the following entries:

- Download
- Show entry
- Show link
- Edit entry
- Delete entry
- Move
- Version
- Lock comments section

Screenshot 1:

![scr_cfiles_context_short](https://user-images.githubusercontent.com/20532633/161553731-061ddecd-3818-4c08-9450-e6963f4cc376.png)

Others in the exact same list have longer context menus with the following entries:

- Download
- Show entry
- Show Link
- Edit entry
- Delete item
- Move
- Versions
- Themes
- Change to "Public
- Lock comment section
- Disable notifications / Enable notifications

Screenshot 2:

![scr_cfiles_context_long](https://user-images.githubusercontent.com/20532633/161553741-d3456160-93c8-4049-9f3b-25c4200d2fa7.png)

This doesn't seem right to me apart from missing translations ("Versions").
Or do I have a comprehension problem here? If so, please clarify.

Thanks in advance

**Comment by yurabakhtin** [comment]
@psg-webdev We have more menu entries only for files which were uploaded through file manager, because in such case the file is created as separate wall entry and we can see it in space/user stream, so only for such files we can display menu entry like `Change to "Public"`. But if a file was attached to some post content then it is not separate wall entry and we cannot use some options for such files.

@luke- Do you agree?

**Comment by yurabakhtin** [comment]
@psg-webdev Yes, it depends on the uploading way, but you mixed up, because it works like this:

- If the file was uploaded without context (post) it has the extended menu, because here it is a separate wall entry, so it can be private/public, can be commented, can has topics and etc. i.e. it can has all options as normal post.
- If the file was uploaded in the context of a post (as attachment) then only a few items in the menu, because it is not a wall entry i.e. it cannot has the options what can be applied to normal post.
