### ISSUE TITLE
Obtain a public link file visible by non members in a private space

### ISSUE THREAD

**Issue by atdqm** [humhub/cfiles#170]
When someone download a file in a private space, he can share a public link. So the file is no more private.

To do that : 
I go in the file menu, I check a folder
![image](https://user-images.githubusercontent.com/112695767/219005678-923573d5-6671-4b04-970f-0c27d62544ef.png)

I click on the "Selected items" menu and I choose "Make Public"
![image](https://user-images.githubusercontent.com/112695767/219005856-e477c02b-a487-43f4-80bd-c430dab7ff64.png)

The folder becomes public
![image](https://user-images.githubusercontent.com/112695767/219006021-159bb452-069b-4a13-bb81-bd18f9a5fd1e.png)

In the folder files are public
![image](https://user-images.githubusercontent.com/112695767/219006254-aaf8baab-322c-487f-b4e1-f99cb6ffbd1a.png)

I can display the URL (also swtich the status Private / Public and if it's private I can make it public again...)
![image](https://user-images.githubusercontent.com/112695767/219007458-195cbc4a-c7d7-44f7-99f5-a1a8806d8f2a.png)

and copy it and share it to other people who are not in the private space
![image](https://user-images.githubusercontent.com/112695767/219006866-f9a1daee-9e05-4084-962e-6cc9e4eb69cd.png)

More discussion is here : https://community.humhub.com/content/perma?id=264761

**Comment by atdqm** [comment]
I add that the link is "working" : a non member of the private space who obtains the link can download the file

**Comment by timmwille** [comment]
This is linked to Issue #6 right?

I noticed with an integration of OnlyOffice if the link is shared as "edit" option to Gusts, it will break the history (as not "User/Account" is defined for the Gust edit) → is there an issue for this (I looked, but maybe it got fixed already?)

**Comment by yurabakhtin** [comment]
As I understand for private Space we don't allow to see a Folder by URL if user has no permission to see the Private Space, it is restricted like this:

![folder_restrict](https://user-images.githubusercontent.com/6995524/227501600-96d63fd6-feae-4223-8c28-ebbbf7b62299.png)

but if we open similar URL of a File then such request is not restricted and any user can download the File, because the URL has format like this `http://humhub.local/file/file/download?guid=cb292a8f-2af5-455a-9ad7-3248b1c41f24&download=1`.
So such file URLs should restricted for user without permissions to view a Private Space.

**Comment by yurabakhtin** [comment]
@luke- Fixed in core PR https://github.com/humhub/humhub/pull/6191.

**Comment by funkycram** [comment]
Tested with Humhub 1.14.0-beta.2 and Files module 0.15.1, but without @yurabakhtin patch (https://github.com/humhub/humhub/pull/6191).
I have, for the link `/file/file/download?guid=d86169e5-2011-44fd-9908-588aa85fefad&download=1`:
![image](https://user-images.githubusercontent.com/23310825/229770112-9a22e8d2-3e24-4f9e-94aa-83d7afc1bfb6.png)

So perhaps https://github.com/humhub/humhub/pull/6191 is useless now with this Humhub version?

@luke- I thought it was because of https://github.com/humhub/humhub/pull/6159 which should be merged into Humhub 1.14.0-beta.1 if we read the https://github.com/humhub/humhub/blob/develop/CHANGELOG-DEV.md, but it is not in the release https://github.com/humhub/humhub/releases

I've checked the code, and https://github.com/humhub/humhub/pull/6159 is not merged (e.g. protected/humhub/modules/space/modules/manage/jobs/ChangeContentVisibilityJob.php is not present).

So I don't understand why I get "Insufficient permissions!" on a public file in a private space even without https://github.com/humhub/humhub/pull/6191

**Comment by luke-** [comment]
Normally, a Space with Private visibility should not have any Public content. With PR #6159 we ensure this when a Space is changed to "Private" afterwards. To convert all Public content to Private visibility.

For me it looks like the CFile module has a bug here when it offers the possibility of "Public" folders. This checkbox should not be available.
