### ISSUE TITLE
Downloading renamed files

### ISSUE THREAD

**Issue by Semir1212** [humhub/cfiles#203]
HH 1.15.3
Files 0.16.3

- Upload file
- Rename
- Download

--> Downloaded file has initial name

**Comment by yurabakhtin** [comment]
@luke- The problem was in browser caching, i.e. if url is not changed after previous downloading then browser downloads the file with same name from cache.
We already fixed similar issue after update a file content with adding url param `hash_sha1` with value like `6d2c467f`, but this param is not updated when file name is changed. This fix is  from core side.
So I have decided to add a new param `hash_name` which 4 first chars of `sha1(File->file_name)`, e.g. `hash_name=ac1e` and have done this only for this module because I think file name can be changed only by this module.
PR https://github.com/humhub/cfiles/pull/204.
