### ISSUE TITLE
Text Editor in file Edit - Image insert doen't work properly

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/cfiles#226]
HHv1.55 - Files Version 0.16.6
**Steps to reproduce:**

1. Open a space
2. Clic "Files" in right menu
3. Right clic on a file
4. Select "Edit". A modal is displayed. You can edit the post.
5. In editor's menu click "upload file".
6. Upload an image.
7. The image is displayed in editor. 
8. So far So good.

And now the issue:
**You cannot modify the image size** 

Go back to the stream
Open the post
**Same issue - You cannot modify the image size**

**Comment by Gilbertdelyon** [comment]
Addition:
Different behavoiur in HH1.15 and HH1.16 (File Version 0.16.6 in both)

1. **In HHv1.15 you get this:**
 ![image](https://github.com/humhub/cfiles/assets/91057837/9262d102-2d88-4afb-bfe5-ff45f0d5dd9e)
 
 
2. **In HHv1.16 you get only this**
 ![image](https://github.com/humhub/cfiles/assets/91057837/87c11936-bd65-4b61-a598-c6adb96bff8f)

**Comment by luke-** [comment]
Does this only affect images in the CFiles module RichText Editor?

e.g. Wiki, Polls, Profile About, are not affected?

**Comment by Gilbertdelyon** [comment]
As far as I can see
**HH1.15**

1. Polls: it works 
2. Wiki: itworks
3. Profile/About: No Richtex editor (only textarea)

**HH1.16**

1. Polls: it works 
2. Wiki: it works  50% (You can resize images but there is only one   item ("load file") in dropdown menu)
![image](https://github.com/humhub/cfiles/assets/91057837/b094276a-dc9b-4dcf-bad8-360c19b50425)
3. Profile/About: No Richtex editor (only textarea)

**Comment by luke-** [comment]
Actually, there should be no difference here.

@yurabakhtin Can you take a look?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub-prosemirror/pull/146 - fix visibility of the edit image button, it was hidden because its z-index was less modal window z-index.

> Actually, there should be no difference here.

New options for the upload menu were implemented [here](https://github.com/humhub/humhub-prosemirror/issues/121) for v1.16.

The additional options go from the upload button if it exists on a form:

![upload-options](https://github.com/humhub/cfiles/assets/6995524/9e8e2ce8-06e3-49b3-852a-dee08802e8f2)

but some forms have no the upload button so we have there only single "Upload File":

![no-options](https://github.com/humhub/cfiles/assets/6995524/39ce663d-1dd9-4a99-8324-7369de3be6e0)

Should we find a solution for such case?

**Comment by Gilbertdelyon** [comment]
Hello,
May I also remind you the initial post an of this issue: (**cannot modify image size in editor**) 
I dont know if it's connected to the upload button issue.
May be I should have post 2 different issues. Sorry.

**Comment by yurabakhtin** [comment]
> May I also remind you the initial post of this issue: (**cannot modify image size in editor**)

@Gilbertdelyon Hello, as I wrote in the comment above, the bug has been fixed in the PR https://github.com/humhub/humhub-prosemirror/pull/146, and it will be in next release.

> I dont know if it's connected to the upload button issue.
May be I should have post 2 different issues. Sorry.

No, it is not related. The options "Image" and "Horizontal rule" were deleted from the version 1.16.
