### ISSUE TITLE
Move files/folders to different Space 

### ISSUE THREAD

**Issue by Oremountainflorian** [humhub/cfiles#84]
Right now, it isn't possible to move files/folders from one space to another (dependent on the space membership of the user doing it). This would be an useful feature.

**Comment by luke-** [comment]
@yurabakhtin We need to implement some Interface here. Some contents types (e.g. Posts) can moved.
![image](https://user-images.githubusercontent.com/4736168/127670810-8be895d1-c502-48d4-8cb6-83aff9638986.png)

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/cfiles/pull/126: I didn't implement new interface, I just activated already implemented by class property `public $canMove = true;`:

<img width="606" alt="move_feature" src="https://user-images.githubusercontent.com/6995524/128482406-a0281290-1254-4e4e-9bff-9aa356162b7e.png">

Please note on moving to another Space the files will be moved into the root folder of the new Space.

I have done this only for files, and not for folders because they are not displayed on space stream, it is disabled by `public $streamChannel = null;` here https://github.com/humhub/cfiles/blob/master/models/Folder.php#L53, however wall entry files for folders are not deleted yet.

**Comment by luke-** [comment]
@yurabakhtin Thanks. The move to the root folder is ok.

But it would be also good if you could move folders. With the issue the feature would be enabled also for non stream entries.
See:  https://github.com/humhub/cfiles/issues/127

**Comment by yurabakhtin** [comment]
@luke- Yes, we can implement this, but I suggest firstly to merge this PR https://github.com/humhub/cfiles/pull/126 into `master`, then merge `master` into the PR https://github.com/humhub/cfiles/pull/131 and there I will can add this feature for folders, because as I see the code can be factorized between models `File` and `Folder` through their abstract `FileSystemItem`, I mean at least the code https://github.com/humhub/cfiles/pull/126/files#diff-b38d0e428b255b7854c669e14d16f5f093b27ca0c01c084f6860c02606abe238R210-R223 that currently is applied only for `File` model.

**Comment by luke-** [comment]
@yurabakhtin Ok, I merged #126.

**Comment by yurabakhtin** [comment]
@luke- After merging I have implemented the folder moving in the commit https://github.com/humhub/cfiles/commit/dbec8e79e300b269984a8bde0e6f39be3e82fd04.
This issue can be closed.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
